/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.theitshop;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class ContainerAutoConfigTest {
    @RunContainersByMethodAutoConfig
    @Test void appHasAGreeting() throws InterruptedException {
        assertTrue(true);
    }
}
