name: TestsRunner
on: [push]
jobs:
  tests:
    name: "Tests - Java ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Gradle Setup
        uses: gradle/gradle-build-action@v2
      - name: Pull required test container
        uses: docker pull testcontainers/ryuk:0.3.3
      - name: Run Gradle Build
        uses: ./gradlew build
